### ISSUE TITLE
[feature] ability to set timestamp in sendNow

### ISSUE THREAD

**Issue by ericallam** [honeycombio/libhoney-js#39]
Currently it isn't possible to set the event timestamp using `sendNow`. Ideally if the data passed into `sendNow` had a `timestamp` field, that would be used as the timestamp of the event.

**Comment by npapagna** [comment]
I ran into this one today.

If the `Timestamp` field is passed to `sendNow` as part of the payload, I end up with duplicated `Timestamp` fields displayed in the trace data:

```
libhoney.sendNow({
   ...,
   Timestamp: new Date().toISOString(),
  ...
});
```

It looks like one is assigned by Honecomb at the moment the event arrives, and the other is the one I provided.

Note that when I manually create an event and override the timestamp property, everything works as expected:

```
const event = libhoney.newEvent();

event.timestamp = new Date().toISOString();
event.add({...});

event send();
```

**Comment by MikeGoldsmith** [comment]
This is because the func `sendNow` creates a new event and adds the map of fields passed in as the event attributes. When an event is created, it sets the event's timestamp field (like in the manual example by @npapagna). It does not check the fields for a `timestamp` field and use that for the event.

An sendNow variant that took the timestamp (eg `sendNowWithTimestamp`) would work. This isn't something we're planning on doing right now though.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
