### ISSUE TITLE
Include node version as field in all events

### ISSUE THREAD

**Issue by allyjweir** [honeycombio/libhoney-js#49]
Similar to the inclusion of a user agent string, include the node version of the process sending the event.

This would be similar to the way beeline-nodejs sends the node version as part of its events. See here for its implementation detail: https://github.com/honeycombio/beeline-nodejs/blob/d1895731cd52e1fd848fe62f6bb5457c678aeec5/lib/api/libhoney.js#L221

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
