### ISSUE TITLE
Queued responses aren't garbage collected, leaking memory

### ISSUE THREAD

**Issue by cwill** [honeycombio/libhoney-js#71]
I noticed a fairly significant change in memory usage in my Node process after adjusting the sample rate for a high-frequency event, which led me to find that `libhoney` leaks memory proportional to the number of events that have been sent, up to a ceiling that's proportional to the size of the response queue.

Appropriately enough, the data collected we're collecting via `libhoney` helped diagnose the root cause -- we include the total allocated process memory in each event and after reducing the size of the event queue from 10k to 1k events and disabling response queueing entirely, we found that memory usage dropped by about 60%.
<img width="949" alt="Screen Shot 2020-01-15 at 2 24 09 PM" src="https://user-images.githubusercontent.com/1686521/86306517-59f0df00-bbc9-11ea-8240-c43784430bc5.png">

It looks like the bug is in `_responseCallback()`: https://github.com/honeycombio/libhoney-js/blob/4209b252657dc0e8441197a64a709f2624a0da8b/src/libhoney.js#L120

Responses are pushed to the response queue on receipt, but even if the events are being consumed, they're never removed and so can't be garbage collected. With default settings this causes libhoney to eventually consume `(10,000 * average_response_size)` bytes, so if response objects are reasonably large (more than a few Kb) this can approach a couple hundred Mb total.

Happy to try drafting a PR for this, but leaving record here since I'm unsure if I'll have time to anytime soon.

**Comment by cwill** [comment]
After reading in the issue backlog a bit more, looks like this may have some overlap with https://github.com/honeycombio/libhoney-js/issues/1

**Comment by toshok** [comment]
yeah, we looked at the code for the default response callback last night and ... ugh yeah that's not working as any reasonable person would expect.

We do have a max response queue size config parameter, but it's not used correctly (it limits when we stop adding to the queue, but not the actual length of the queue).  We also never clear the queue, so once you get up to >= max queue size, we keep those responses around for ever - and we keep sending them in the callback.  We never send the newer responses.  Totally broken.

A couple things we should probably do:

1. stop keeping a reference to the queued responses at all (they're being passed to the callback, but we never _clear_ them, even if there's a listener on the other end, and there's no API to do so)  Just send them in the callback and let them go.
2. maybe drop that config parameter?  there's no reason to have a max queue size if they go away immediately - the callback target code can handle that.

Since 1 means removing `this._responseQueue`, until a major bump we likely need to fix the behavior such that we only keep max-queue-size responses _after_ the callback (so users can still get all the responses in the callback), and we keep the _new_ responses, not the old ones.

something like:

```
  _responseCallback(responses) {
    // this method after minor bump
    this._responseQueue = this._responseQueue.concat(responses);
    this.emit("response", this._responseQueue);
    if (this._responseQueue.length < this._options.maxResponseQueueSize) {
        this._responseQueue = this._responseQueue.slice(-this._options.maxResponseQueueSize);
    }
    // this method after major bump
    this.emit("response", responses);
  }
```

**Comment by cwill** [comment]
Thanks for looking into it!

I'd agree with (1) -- As far as I'm aware, it's typical `EventEmitter` etiquette that if a handler cares about not missing any events, it should be registered before any events have a chance to be generated, so losing the past buffered responses if they weren't consumed by a handler seems acceptable to me.

If the response queue is eliminated, (2) seems to directly follow, but until then it's probably useful to be able to have a hard limit on memory usage to protect against a situation where some non-preemptable piece of code is hogging the nodejs event loop for whatever reason and preventing the queue from getting consumed.

All that said, in my case I never actually register a handler for the `"response"` event -- as a stopgap I wonder if something like this might improve the most-common case?:
- if there's no external consumer for responses (`this.listenerCount("response") === 0`), throw out responses immediately
- If there's at least one listener, keep compatibility with the existing behavior
That'd sidestep breaking any existing dependencies on the current behavior but remove any impact on any implementation that doesn't use this part of the library.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
